### PR TITLE
Feature/single cell doublet finder

### PR DESCRIPTION
**Pull request by astha94**
Still need to add the 3rd test, but it seems from the JSON that these two tests are exactly the same:

mev-sctk-doubletfinder
mev-sctk-doubletcells

But have added doublet detection and generalized it so that can be reviewed

### CODE REVIEW

**Comment by blawney** [comment]
I'm seeing a few files that are the result of the "templating process". That is, files like `vagrant/env.txt` have config variables, etc. that are the result of editing `vagrant/env.tmpl`. 

In total, I see the following which should be removed from the latest commit:
- projects/web-mev/src/index.html
- projects/web-mev/src/app/jwtConfig.ts
- projects/web-mev/src/app/sentry-error-handler.ts
- projects/web-mev/src/environments/environment.ts

Everything else looks good by my eye. Haven't built using this commit yet, however.

**Comment by blawney** [comment]
I pulled a clean version of this branch and tried to build locally using Vagrant. It failed, giving me the following:

```
vagrant up
 ...
 <bunch of stuff>
 ...
    default: 
    default: > web-mev@2.0.0 build
    default: > ng build
    default: Compiling @angular/animations : es2015 as esm2015
    default: Compiling ngx-csv-parser : es2015 as esm2015
    default: 
    default: ERROR in projects/web-mev/src/app/d3/components/sctk-doublet-detection/sctk-doublet-detection.component.ts:344:28 - error TS2345: Argument of type '[string, unknown][]' is not assignable to parameter of type '(number | { valueOf(): number; })[]'.
    default:   Type '[string, unknown]' is not assignable to type 'number | { valueOf(): number; }'.
    default:     Type '[string, unknown]' is not assignable to type 'number'.
    default: 
    default: 344     const data_ready = pie(Object.entries(data));
    default:                                ~~~~~~~~~~~~~~~~~~~~
    default: projects/web-mev/src/app/d3/components/sctk-doublet-detection/sctk-doublet-detection.component.ts:372:5 - error TS2769: No overload matches this call.
    default:   Overload 1 of 4, '(name: string, value: null): Selection<Element | Window | Document | SVGPathElement | EnterElement, unknown, SVGGElement, unknown>', gave the following error.
    default:     Argument of type '(this: Element | Window | Document | SVGPathElement | EnterElement, d: unknown) => unknown' is not assignable to parameter of type 'null'.
    default:   Overload 2 of 4, '(name: string, value: string | number | boolean): Selection<Element | Window | Document | SVGPathElement | EnterElement, unknown, SVGGElement, unknown>', gave the following error.
    default:     Argument of type '(this: Element | Window | Document | SVGPathElement | EnterElement, d: unknown) => unknown' is not assignable to parameter of type 'string | number | boolean'.
    default:       Type '(this: Element | Window | Document | SVGPathElement | EnterElement, d: unknown) => unknown' is not assignable to type 'true'.
    default:   Overload 3 of 4, '(name: string, value: ValueFn<Element | Window | Document | SVGPathElement | EnterElement, unknown, string | number | boolean>): Selection<...>', gave the following error.
    default:     Type 'unknown' is not assignable to type 'string | number | boolean'.
    default:       Type 'unknown' is not assignable to type 'true'.
    default: 
    default: 372     svg
    default:         ~~~
    default: 
    default: 373       .selectAll('allSlices')
    default:     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    default: ... 
    default: 376       .attr('d', arc)
    default:     ~~~~~~~~~~~~~~~~~~~~~
    default: 377       .attr('fill', d => color(d.data[0]))
    default:     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    default: 
    default:   node_modules/@types/d3-selection/index.d.ts:86:58
    default:     86 export type ValueFn<T extends BaseType, Datum, Result> = (this: T, datum: Datum, index: number, groups: T[] | ArrayLike<T>) => Result;
    default:                                                                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    default:     The expected type comes from the return type of this signature.
    default: projects/web-mev/src/app/d3/components/sctk-doublet-detection/sctk-doublet-detection.component.ts:377:34 - error TS2339: Property 'data' does not exist on type 'unknown'.
    default: 
    default: 377       .attr('fill', d => color(d.data[0]))
    default:                                      ~~~~
    default: projects/web-mev/src/app/d3/components/sctk-doublet-detection/sctk-doublet-detection.component.ts:443:22 - error TS2769: No overload matches this call.
    default:   Overload 1 of 4, '(name: string, value: null): Selection<SVGCircleElement, string, SVGGElement, unknown>', gave the following error.
    default:     Argument of type 'ScaleOrdinal<string, unknown>' is not assignable to parameter of type 'null'.
    default:   Overload 2 of 4, '(name: string, value: string | number | boolean, priority?: "important"): Selection<SVGCircleElement, string, SVGGElement, unknown>', gave the following error.
    default:     Argument of type 'ScaleOrdinal<string, unknown>' is not assignable to parameter of type 'string | number | boolean'.
    default:       Type 'ScaleOrdinal<string, unknown>' is not assignable to type 'true'.
    default:   Overload 3 of 4, '(name: string, value: ValueFn<SVGCircleElement, string, string | number | bo
    default: olean>, priority?: "important"): Selection<SVGCircleElement, string, SVGGElement, unknown>', gave the following error.
    default:     Argument of type 'ScaleOrdinal<string, unknown>' is not assignable to parameter of type 'ValueFn<SVGCircleElement, string, string | number | boolean>'.
    default:       Type 'unknown' is not assignable to type 'string | number | boolean'.
    default:         Type 'unknown' is not assignable to type 'true'.
    default: 
    default: 443       .style('fill', color)
    default:
```
Seems like this could be related to stricter type-checking or something?

**Comment by blawney** [comment]
It builds! There's a couple small things that I noticed before I merge:
- It says "placeholder text" for the output. I'll provide something for that
- CSS for spacing the button below the chart view (e.g. `margin-top`)
- When the donut grows upon clicking, it goes outside the viewbox and the top/bottom are cut off.

**Comment by astha94** [comment]
> It builds! There's a couple small things that I noticed before I merge:
> 
> * It says "placeholder text" for the output. I'll provide something for that
> * CSS for spacing the button below the chart view (e.g. `margin-top`)
> * When the donut grows upon clicking, it goes outside the viewbox and the top/bottom are cut off.

Following up on the first point, do you have the "placeholder text" that can be used for describing the 3 tools for singlet cell doublet detection?

**Comment by astha94** [comment]
I've updated the previous "placeholder text" entries and modified the CSS. Ready for further review.

**Comment by blawney** [comment]
CSS looks better. Almost there.

There is an issue I'm noticing with respect to group selection and the toggle of the "save as a sample set" button. Steps to recreate:
- Click on the arc (e.g. the singlet part). That portion grows and the button becomes active. All good so far
- Now, click on the doublet part of the arc. I notice the following:
  - The button becomes inactive
  - The singlet arc remains enlarged, but the doublet part does *not* become enlarged

A subsequent second click on the doublet arc ends up enlarging both arcs (the whole donut) and the button becomes active again. 

This likely stems from the fact that we didn't fully discuss the behavior of the donut upon selection. I think it's the most "natural" to only allow one arc to be selected at a time. Choosing to make a sample set using both arcs is kind of trivial since that ends up being all the samples of the entire dataset.

So I think the desired behavior should be the following. Assume that one has already clicked and enlarged the "singlet" arc.
- Clicking on the doublet arc reduces the singlet arc and grows the doublet arc. Button remains active
- Clicking on the singlet arc (i.e. the one that is already selected) will shrink that part and the button will become inactive. Basically a toggle.
- Clicking outside the donut plot does NOT unselect any parts.
- We should not be able to select both arcs simultaneously.

**Comment by astha94** [comment]
I've updated the donut plot to fulfill the desired toggle behavior and the feature is ready for further review.

**Pull request merged**
